/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umtas.uas;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MainKasir extends javax.swing.JFrame {

    ProdukService produkService = new ProdukService();

    /**
     * Creates new form MainKasir
     */
    public MainKasir() {
        initComponents();
        refreshTableProduk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kodeProdukField = new javax.swing.JTextField();
        namaProdukField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        hargaField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kodeProdukField.setText("Tuliskan kode produk");
        kodeProdukField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kodeProdukFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kodeProdukFieldMouseExited(evt);
            }
        });
        kodeProdukField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeProdukFieldActionPerformed(evt);
            }
        });

        namaProdukField.setText("Tuliskan nama produk");
        namaProdukField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaProdukFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                namaProdukFieldMouseExited(evt);
            }
        });

        jLabel1.setText("Kode Produk");

        jLabel2.setText("Nama Produk");

        qtyField.setText("Tuliskan jumlah pembelian");
        qtyField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qtyFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qtyFieldMouseExited(evt);
            }
        });
        qtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyFieldActionPerformed(evt);
            }
        });

        hargaField.setText("berapa harga satuannya");
        hargaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hargaFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hargaFieldMouseExited(evt);
            }
        });
        hargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Qty");

        jLabel4.setText("Harga");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Produk", "Nama Produk", "Qty", "Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("<html>saya Fathi Makia Madani bersungguh-sungguh. menyatakan <br>\nbahwa aplikasi yang saya buat, benar-benar buatan sendiri. Jika aplikasi bukan buatan<br>saya sendiri, maka saya berani untuk mempertanggung jawabkannya dikemudian hari</html>"); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel6.setText("Total Harga");

        addButton.setText("Tambahkan");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("APLIKASI KASIR");

        jLabel9.setText("Dibuat oleh : Fathi Makia Madani | C1983207015");

        labelTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(63, 63, 63)
                                .addComponent(labelTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kodeProdukField)
                                            .addComponent(namaProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(156, 156, 156)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(qtyField)
                                                .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(addButton))
                                        .addComponent(jLabel4))))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel9)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(labelTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jLabel5.getAccessibleContext().setAccessibleName("saya Fathi Makia Madani bersungguh-sungguh. menyatakan bahwa aplikasi yang saya buat, benar-benar buatan \\n sendiri. Jika aplikasi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeProdukFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeProdukFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukFieldActionPerformed

    private void hargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        System.out.println(kodeProdukField.getText());
        System.out.println(namaProdukField.getText());
        System.out.println(qtyField.getText());
        System.out.println(hargaField.getText());

        Produk produk = new Produk();
        produk.setId(UUID.randomUUID().toString().replace("-", ""));
        produk.setKodeProduk(kodeProdukField.getText());
        produk.setNamaProduk(namaProdukField.getText());
        produk.setQty(Integer.valueOf(qtyField.getText()));
        produk.setHarga(new BigDecimal(hargaField.getText()));

        produkService = new ProdukService();
        produkService.save(produk);

        refreshTableProduk();
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed

    }//GEN-LAST:event_addButtonKeyPressed

    private void kodeProdukFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kodeProdukFieldMouseEntered
        if (kodeProdukField.getText().startsWith("Tuliskan")) {
            kodeProdukField.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukFieldMouseEntered

    private void namaProdukFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaProdukFieldMouseEntered
        if (namaProdukField.getText().startsWith("Tuliskan")) {
            namaProdukField.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProdukFieldMouseEntered

    private void qtyFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyFieldMouseEntered
        if (qtyField.getText().startsWith("Tuliskan")) {
            qtyField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldMouseEntered
    }
    private void hargaFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargaFieldMouseEntered
        if (hargaField.getText().startsWith("berapa")) {
            hargaField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_hargaFieldMouseEntered
    }
    private void kodeProdukFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kodeProdukFieldMouseExited
        if (kodeProdukField.getText().isEmpty()) {
            kodeProdukField.setText("Tuliskan Kode Produk");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukFieldMouseExited

    private void namaProdukFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaProdukFieldMouseExited
        if (namaProdukField.getText().isEmpty()) {
            namaProdukField.setText("Tuliskan Nama Produk");        // TODO add your handling code here:
    }//GEN-LAST:event_namaProdukFieldMouseExited
    }
    private void qtyFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyFieldMouseExited
        if (qtyField.getText().isEmpty()) {
            qtyField.setText("Tulisan Jumlah Pembelian");       // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldMouseExited
    }
    private void hargaFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargaFieldMouseExited
        if (hargaField.getText().isEmpty()) {
            hargaField.setText("berapa Harga satuannya");    // TODO add your handling code here:
    }//GEN-LAST:event_hargaFieldMouseExited
    }
    private void qtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldActionPerformed

    public void refreshTableProduk() {
        java.util.List<Produk> ls = produkService.getAllProduk();
        Object[][] rs = new Object[ls.size()][5];
        BigDecimal total = BigDecimal.ZERO;
        for (int i = 0; i < ls.size(); i++) {
            rs[i][0] = ls.get(i).getKodeProduk();
            rs[i][1] = ls.get(i).getNamaProduk();
            rs[i][2] = ls.get(i).getQty();
            rs[i][3] = NumberFormat.getCurrencyInstance(new Locale("in", "ID")).format(ls.get(i).getHarga());
            rs[i][4] = NumberFormat.getCurrencyInstance(new Locale("in", "ID")).format(ls.get(i).getHarga().multiply(new BigDecimal(ls.get(i).getQty())));
            total = total.add(ls.get(i).getHarga().multiply(new BigDecimal(ls.get(i).getQty())));
        }

        DefaultTableModel dtm = new DefaultTableModel(rs, new String[]{"Kode Produk", "Nama Produk", "Qty", "Harga", "Sub Total"});
        jTable1.setModel(dtm);

        labelTotal.setText(NumberFormat.getCurrencyInstance(new Locale("in", "ID")).format(total));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainKasir().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kodeProdukField;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTextField namaProdukField;
    private javax.swing.JTextField qtyField;
    // End of variables declaration//GEN-END:variables
}
